services:
  - type: web
    name: estin-detection-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: estin-detection-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_PASSWORD
        sync: false